### ISSUE TITLE
Query prikazuje broj dobavljaca ciji se br_racuna sastoji od vise od jedne rijeci

### ISSUE THREAD

**Issue by EnisMulic** [FITCommunity/Baze-Podataka-2#2]
https://github.com/FITCommunity/Baze-Podataka-2/blob/4d36dc5a5655143ec7a39bbce17a3a378f4a1c6e/Ispiti/2020-06-23/BP2_2020-06-23_Rjesenje.sql#L273-L282

**Comment by haris-hindic** [comment]
--Poredi duzinu dobavljac_br_rac uz prethodno odstranjene brojeve(0001) sa duzinom prve rijeci iz naziv_dobavljaca uz uslov da naziv_dobavljaca ima vise od jedne rijeci i na taj nacin ove dobavljac_br_rac sa vecom duzinom od prve rijeci se prebroje i dobijemo koliko ih ukupno ima sastavljenih iz vise od jedne rijeci

----------------------------------------------------

select  COUNT(*) as prebrojano 
from   dobavljac 
where LEN(SUBSTRING(dobavljac_br_rac, 0, CHARINDEX('0', dobavljac_br_rac))) > 
           LEN(SUBSTRING(naziv_dobavljaca, 0, CHARINDEX(' ', naziv_dobavljaca))) and 
	   CHARINDEX(' ', naziv_dobavljaca) != 0
